### ISSUE TITLE
Name change not detected

### ISSUE THREAD

**Issue by mkutmon** [wikipathways/WPReactomeUploader#2]
* http://wikipathways.org/index.php/Pathway:WP2655
renamed to 
http://wikipathways.org/index.php/Pathway:WP4092

**Comment by mkutmon** [comment]
* http://wikipathways.org/index.php/Pathway:WP3817
* http://wikipathways.org/index.php/Pathway:WP4067

Same Reactome id, different name

**Comment by mkutmon** [comment]
* http://wikipathways.org/index.php/Pathway:WP4045
* http://wikipathways.org/index.php/Pathway:WP2732

same reactome id, different name

**Comment by egonw** [comment]
http://wikipathways.org/index.php/Pathway:WP1909 is now http://wikipathways.org/index.php/Pathway:WP4130

**Comment by egonw** [comment]
http://wikipathways.org/index.php/Pathway:WP1935 is now http://wikipathways.org/index.php/Pathway:WP4077

(with a bit split out into another pathway, I think)

**Comment by mkutmon** [comment]
* http://wikipathways.org/index.php/Pathway:WP3797 
renamed to
* http://wikipathways.org/index.php/Pathway:WP4081

**Comment by mkutmon** [comment]
* http://wikipathways.org/index.php/Pathway:WP2749
renamed to
* http://wikipathways.org/index.php/Pathway:WP3836

(vitamin D in separate pathway)

**Comment by mkutmon** [comment]
* http://wikipathways.org/index.php/Pathway:WP1867
renamed to 
* http://wikipathways.org/index.php/Pathway:WP4057

**Comment by egonw** [comment]
* http://wikipathways.org/index.php/Pathway:WP3828
renamed to
* http://wikipathways.org/index.php/Pathway:WP4044

**Comment by mkutmon** [comment]
* http://wikipathways.org/index.php/Pathway:WP1870
renamed to 
* http://wikipathways.org/index.php/Pathway:WP4076

**Comment by mkutmon** [comment]
* http://wikipathways.org/index.php/Pathway:WP1871
renamed to 
* http://wikipathways.org/index.php/Pathway:WP4040

**Comment by egonw** [comment]
* http://wikipathways.org/index.php/Pathway:WP3551
renamed to 
* http://wikipathways.org/index.php/Pathway:WP3834
renamed to
* http://wikipathways.org/index.php/Pathway:WP4060

**Comment by mkutmon** [comment]
* http://wikipathways.org/index.php/Pathway:WP1872 
renamed to
* http://wikipathways.org/index.php/Pathway:WP4078

**Comment by egonw** [comment]
* http://wikipathways.org/index.php/Pathway:WP3828
renamed to
* http://wikipathways.org/index.php/Pathway:WP4044

**Comment by mkutmon** [comment]
* http://wikipathways.org/index.php/Pathway:WP2754 
renamed to
* http://wikipathways.org/index.php/Pathway:WP4056

**Comment by egonw** [comment]
OK, this one would not have been found by just looking at names:

* http://wikipathways.org/index.php/Pathway:WP1904
renamed to:
* http://wikipathways.org/index.php/Pathway:WP4127

**Comment by mkutmon** [comment]
* http://wikipathways.org/index.php/Pathway:WP1839
renamed to 
* http://wikipathways.org/index.php/Pathway:WP4062

**Comment by mkutmon** [comment]
* http://wikipathways.org/index.php/Pathway:WP1800 
renamed to 
* http://wikipathways.org/index.php/Pathway:WP4123

**Comment by mkutmon** [comment]
old pathways are updated with content from new pathways - new pathways are deleted.
