### ISSUE TITLE
Pathway not updated

### ISSUE THREAD

**Issue by mkutmon** [wikipathways/WPReactomeUploader#3]
"Chromatin modifying enzymes" http://wikipathways.org/index.php/Pathway:WP3362 - links to http://www.reactome.org/PathwayBrowser/#DIAGRAM=3247509. 
Pathway was not updated in last release but is still available on Reactome - why wasn't it updated?

**Comment by mkutmon** [comment]
This pathway also wasn't updated even though name and id didn't change: http://wikipathways.org/index.php/Pathway:WP3577)

**Comment by mkutmon** [comment]
http://wikipathways.org/index.php/Pathway:WP1808 wasn't updated even though pathway still exists on Reactome - http://www.reactome.org/PathwayBrowser/#DIAGRAM=376172

**Comment by mkutmon** [comment]
http://wikipathways.org/index.php/Pathway:WP1828 wasn't updated but still exists on Reactome with same id

**Comment by mkutmon** [comment]
http://wikipathways.org/index.php/Pathway:WP1851 still exists on Reactome!

**Comment by mkutmon** [comment]
http://wikipathways.org/index.php/Pathway:WP3796

**Comment by mkutmon** [comment]
http://wikipathways.org/index.php/Pathway:WP3498

**Comment by mkutmon** [comment]
http://wikipathways.org/index.php/Pathway:WP3557

**Comment by DeniseSl22** [comment]
This should all be fixed with Upload 62
