### ISSUE TITLE
Pathway seems to be deleted on Reactome

### ISSUE THREAD

**Issue by mkutmon** [wikipathways/WPReactomeUploader#4]
http://wikipathways.org/index.php/Pathway:WP1817 not updated and I can't find it on Reactome - link doesn't work anymore

**Comment by mkutmon** [comment]
http://wikipathways.org/index.php/Pathway:WP2704 doesn't seem to exist on Reactome anymore (http://www.reactome.org/PathwayBrowser/#DIAGRAM=1059683) - possibly replaced by: http://wikipathways.org/index.php/Pathway:WP4122

**Comment by egonw** [comment]
Redundant too:

http://wikipathways.org/index.php/Pathway:WP3504 -> split up into several others.

Others in the same curation effort that can be removed:

http://wikipathways.org/index.php/Pathway:WP2704 -> is now: http://wikipathways.org/index.php/Pathway:WP4122
http://wikipathways.org/index.php/Pathway:WP2732 -> is now: http://wikipathways.org/index.php/Pathway:WP4045
http://wikipathways.org/index.php/Pathway:WP3817 -> is now: http://wikipathways.org/index.php/Pathway:WP4067

**Comment by mkutmon** [comment]
http://wikipathways.org/index.php/Pathway:WP2764

**Comment by DeniseSl22** [comment]
This is all fixed with upload of version 62.
