### ISSUE TITLE
Reactome id changed but new pathway wasn't added

### ISSUE THREAD

**Issue by mkutmon** [wikipathways/WPReactomeUploader#5]
http://wikipathways.org/index.php/Pathway:WP3554 is pointing to Reactome id: 199983. This one doesn't exist anymore. But I search for "Golgi to ER Retrograde Transport", I find the following pathway: http://reactome.org/PathwayBrowser/#/R-HSA-8856688 (which wasn't added in the last release)

**Comment by DeniseSl22** [comment]
This should all be fixed with version 62 upload.
